image: Visual Studio 2019

version: 3.24.{build}.0

clone_folder: c:\projects\ditto

branches:
  # whitelist
  only:
    - master
    
platform:
  - Win43
  - x64

configuration:
  - Release
    
install:
- set INNOSETUPPATH=C:\Program Files (x86)\Inno Setup 6
- set versionFileName=3_24_{build}_0
- set Path=%INNOSETUPPATH%;%PATH%

 
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
build:
  parallel: true
  project: CP_Main_10.sln   

# build_script:
# - echo Building version:%appveyor_build_version%
# - cmd: nuget restore
# - echo Building 32Bit
# - cmd: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=Win32
#- echo Building 64Bit
#- cmd: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=x64

after_build:
- cmd ISCC.exe" /F"DittoSetup_%versionFileName%" "Ditto_Build\DittoSetup\DittoSetup_10.iss"

artifacts:
- path: Ditto_Build\DittoSetup\output\DittoSetup_%versionFileName%.exe
  name: DittoSetup

