image: Visual Studio 2019

version: 3.24.{build}.0

clone_folder: c:\projects\ditto

branches:
  # whitelist
  only:
    - master
    
install:
  - set versionFileName=3_24_%APPVEYOR_BUILD_VERSION%_0

platform:
  - Win32

configuration:
  - Release
 
before_build:
  - nuget restore
 
build:
  parallel: true
  project: CP_Main_10.sln   


#build_script:
#- echo Building version:%appveyor_build_version%
#- cmd: nuget restore
#- echo Building 32Bit
#- cmd: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=Win32
#- echo Building 64Bit
#- cmd: msbuild CP_Main_10.sln /p:Configuration=Release /p:Platform=x64

after_build:
  - C:\Program Files (x86)\Inno Setup 6\iscc /F"DittoSetup_%versionFileName%" "DittoSetup\DittoSetup_10.iss"

artifacts:
  - path: DittoSetup\output\DittoSetup_%versionFileName%.exe
    name: DittoSetup

